[INTERNAL] Rework Issue Reporting
SAP/ui5-tooling pull request #273
Opened 2020-11-10 19:30 UTC by RandomByte

* Centralize issues from all UI5 Tooling modules into the ui5-tooling
  repository
* Use new GitHub issue template structure
* Add Code of Conduct. OSPO recommends the "Contributor Covenant"
* Add SUPPORT.md guiding how to seek general help. This is hinted
  to users when creating a new issue.

2020-11-11 07:53 UTC, KlattG requested changes
Just a few suggestions, otherwise fine.

2020-11-11 07:53 UTC, KlattG commented on .github/ISSUE_TEMPLATE/bug-report.md
> +about: Report an issue with the UI5 Tooling
```suggestion
about: Report an issue with UI5 Tooling
```

2020-11-11 07:53 UTC, KlattG commented on .github/ISSUE_TEMPLATE/bug-report.md
> +    Depending on your issue, consider forking our sample app to reproduce it there: https://github.com/SAP/openui5-sample-app
```suggestion
    Depending on your issue, consider forking our sample app to reproduce it here: https://github.com/SAP/openui5-sample-app
```

2020-11-11 07:53 UTC, KlattG commented on .github/ISSUE_TEMPLATE/feature-request.md
> +about: Request a new feature to be added to the UI5 Tooling
```suggestion
about: Request a new feature to be added to UI5 Tooling
```

2020-11-11 07:53 UTC, KlattG commented on .github/ISSUE_TEMPLATE/feature-request.md
> +A clear and concise description of what the problem is. Ex. I'm always frustrated when {...}
```suggestion
A clear and concise description of the problem, e.g. "I'm always frustrated when {...}"
```

2020-11-11 07:53 UTC, KlattG commented on CODE_OF_CONDUCT.md
> +* Demonstrating empathy and kindness toward other people
```suggestion
* Demonstrating empathy and kindness toward each other
```

2020-11-11 07:53 UTC, KlattG commented on CODE_OF_CONDUCT.md
> +  and learning from the experience
```suggestion
  and learning from our experiences
```

2020-11-11 07:53 UTC, KlattG commented on CODE_OF_CONDUCT.md
> +  overall community
```suggestion
  entire community
```

2020-11-11 07:53 UTC, KlattG commented on CONTRIBUTING.md
> +If you need help setting something up, or if you have questions regarding the UI5 Tooling, please seek help on a community platform like the [SAP Community](https://answers.sap.com/topics/ui5-tooling
```suggestion
If you need help setting something up, or if you have questions regarding UI5 Tooling, please seek help on a community platform like the [SAP Community](https://answers.sap.com/topics/ui5-tooling.html), [StackOverflow](http://stackoverflow.com/questions/tagged/ui5-tooling) or the [`#tooling`](https://openui5.slack.com/archives/C0A7QFN6B) channel of the [OpenUI5 Community Slack](https://ui5-slack-invite.cfapps.eu10.hana.ondemand.com/).
```

2020-11-11 07:53 UTC, KlattG commented on CONTRIBUTING.md
> +For bigger features an RFC (Request for Comment) might be necessary. You should always clarify the need for an RFC with the project contributors upfront. Either via an issue or in our [Slack channel]
```suggestion
For bigger features an RFC (Request for Comment) might be necessary. You should always clarify the need for an RFC with the project contributors upfront. You could do this either by opening an issue or in our [Slack channel](#seeking-help--not-a-bug). You can use [this template](rfcs/0000-template.md) for creating an RFC.
```

2020-11-11 07:53 UTC, KlattG commented on SUPPORT.md
> +If you need help setting something up, or if you have questions regarding the UI5 Tooling, please refrain from opening an issue on GitHub.
```suggestion
If you need help setting something up, or if you have questions regarding UI5 Tooling, please refrain from opening an issue on GitHub. 
```

2020-11-11 10:30 UTC, KlattG approved these changes
LGTM

2020-11-13 10:32 UTC, matz3 approved these changes

2020-11-19 18:41 UTC, merged