[INTERNAL] Document specVersion 2.3
SAP/ui5-tooling pull request #492
Opened 2021-02-09 14:12 UTC by RandomByte

New feature:
Support for "exclude" configuration of component- and library
preload bundles

2021-02-09 16:27 UTC, matz3 approved these changes

2021-02-10 09:00 UTC, KlattG requested changes

2021-02-10 09:00 UTC, KlattG commented on docs/pages/Configuration.md
> +There are two ways to define the set of components preload bundles should be generated for: `paths` (allowing patterns) and `namespaces`. You can also combine both configuration options. Defining any
```suggestion
There are two ways to define the set of components for which preload bundles should be generated. You can either provide `paths` (allowing patterns) or `namespaces`. You can also combine both configuration options. Defining any of them overrides the default preload bundle generation for the root component of `application` projects.
```

2021-02-10 10:25 UTC, KlattG commented on docs/pages/Configuration.md
> +    - `filters`: List of modules declared as glob patterns (resource name patterns) that should be in- or excluded. A pattern ending with a slash '/' will, similarly to the use of a single '*' or dou
```suggestion
    - `filters`: List of modules declared as glob patterns (resource name patterns) that should be in- or excluded. A pattern ending with a slash '/' will, similarly to the use of a single '*' or double '**' asterisk, denote an arbitrary number of characters or folder names. Excludes should be marked with a leading exclamation mark '!'. The order of filters is relevant; a later inclusion overrides an earlier exclusion, and vice versa.
```

2021-02-10 12:05 UTC, KlattG submitted a review, later dismissed
LGTM

2021-02-10 13:14 UTC, matz3 approved these changes

2021-02-10 13:21 UTC, merged