[INTERNAL] Document specVersion 2.5
SAP/ui5-tooling pull request #533
Opened 2021-07-09 16:08 UTC by larskissel

**Thank you for your contribution!** 🙌

To get it merged faster, kindly review the checklist below:

## Pull Request Checklist
- [ ] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-tooling/blob/master/CONTRIBUTING.md#-contributing-code)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-tooling/blob/master/CONTRIBUTING.md#how-to-contribute) section 
- [ ] [No merge commits](https://github.com/SAP/ui5-tooling/blob/master/docs/Guidelines.md#no-merge-commits)
- [ ] [Correct commit message style](https://github.com/SAP/ui5-tooling/blob/master/docs/Guidelines.md#commit-message-style)

2021-07-12 17:25 UTC, RandomByte requested changes
I'm mostly fine with this change However, the whitespace-trimming changes should be reverted

2021-07-12 17:25 UTC, RandomByte commented on docs/index.md
> -Configure your project for use with the UI5 Tooling.
These spaces must be kept. They represent a single line break in markdown. I guess this is caused by a "whitespace trimming" IDE extension you have. Maybe you can exclude `.md` files from it?

2021-07-13 09:25 UTC, KlattG requested changes

2021-07-13 09:25 UTC, KlattG commented on docs/index.md
> +Configure your project for use with the UI5 Tooling.
```suggestion
Configure your project for use with UI5 Tooling.
```

2021-07-13 09:25 UTC, KlattG commented on docs/pages/Configuration.md
> +Starting with [specification version 2.0](#specification-version-20) the configuration is validated according to a JSON schema.
```suggestion
Starting with [Specification Version 2.0](#specification-version-20) the configuration is validated according to a JSON schema.
```

2021-07-13 09:25 UTC, KlattG commented on docs/pages/Configuration.md
> +The schema is also part of the [JSON Schema Store catalog](http://schemastore.org/json/) which is used by the [YAML Language Server](https://github.com/redhat-developer/yaml-language-server).
```suggestion
The schema is also part of the [JSON Schema Store Catalog](http://schemastore.org/json/) which is used by the [YAML Language Server](https://github.com/redhat-developer/yaml-language-server).
```

2021-07-13 09:25 UTC, KlattG commented on docs/pages/Configuration.md
> +A given `copyright` string will be used to fill placeholders like `${copyright}` and `@copyright@` in a projects source code. `|-` is a way to define a multi line string in YAML. For details, please
```suggestion
A given `copyright` string will be used to fill placeholders like `${copyright}` and `@copyright@` in a project's source code. `|-` is a way to define a multi line string in YAML. Check the [YAML Specification](https://yaml.org/spec/1.2/spec.html#id2794534) for details.
```

2021-07-13 09:25 UTC, KlattG commented on docs/pages/Configuration.md
> +Custom configuration that is ignored by the UI5 Tooling.
```suggestion
Custom configuration that is ignored by UI5 Tooling.
```

2021-07-13 09:25 UTC, KlattG commented on docs/pages/Configuration.md
> +For projects of type `library` there is no Component Preload created by default.
```suggestion
For projects of type `library`, no Component Preload is created by default.
```

2021-07-13 09:25 UTC, KlattG commented on docs/pages/Configuration.md
> +You can include certain dependencies into the build process using the builder setting `includeDependency`. By using `includeDependencyRegExp` a regular expression can be used e.g. to specify a namesp
```suggestion
You can include certain dependencies into the build process using the `includeDependency` builder setting . By using `includeDependencyRegExp`, a regular expression can be used, for example to specify a namespace to dynamically select a group of dependencies that have to be included into the build result. By using `includeDependencyTree`, a selected dependency including all of its sub-dependencies is used.
```

2021-07-23 11:21 UTC, RandomByte approved these changes
LGTM

2021-07-23 14:46 UTC, merged