[INTERNAL] CustomTask: Enhance implementation documentation
SAP/ui5-tooling pull request #581
Opened 2021-11-10 17:59 UTC by RandomByte

2021-11-11 07:51 UTC, KlattG requested changes

2021-11-11 07:51 UTC, KlattG commented on docs/pages/extensibility/CustomTasks.md
> +The following code snippets shows an example how a task implementation could look like. This task uses a generic "toMarkdown" library to transform text to [markdown](https://daringfireball.net/projec
```suggestion
The following code snippet shows an example of what a task implementation might look like. This task uses a generic "toMarkdown" library to transform text to [markdown](https://daringfireball.net/projects/markdown/) and writes out the newly created markdown files.
```

2021-11-11 11:57 UTC, KlattG submitted a review, later dismissed
LGTM

2021-11-16 14:37 UTC, matz3 requested changes

2021-11-16 14:37 UTC, matz3 commented on docs/pages/extensibility/CustomTasks.md
> +- **`taskUtil`**: See [details below](http://localhost:8000/pages/extensibility/CustomTasks/#helper-class-taskutil)
```suggestion
- **`taskUtil`**: See [details below](https://sap.github.io/ui5-tooling/pages/extensibility/CustomTasks/#helper-class-taskutil)
```

2021-11-17 14:24 UTC, matz3 approved these changes

2021-11-18 13:59 UTC, merged