[INTERNAL] Add preliminary guide for v3 migration
SAP/ui5-tooling pull request #608
Opened 2022-03-25 13:25 UTC by matz3

2022-04-01 08:50 UTC, matz3 commented on docs/pages/Builder.md
> +Files will be generated automatically for all bundles.
Maybe we should also link to the relevant PR https://github.com/SAP/ui5-builder/pull/695 ?

2022-04-04 12:20 UTC, KlattG requested changes
Just some minor suggestion, otherwise LGTM

2022-04-04 12:20 UTC, KlattG commented on docs/updates/migrate-v3.md
> +process takes place. Existing 'beforeTask' and 'afterTask' configuration of
```suggestion
process takes place. Any existing 'beforeTask' or 'afterTask' configuration of
```

2022-04-04 12:20 UTC, KlattG commented on docs/updates/migrate-v3.md
> +**All UI5 Tooling Modules: Require Node.js >= 16.13.2 / npm >= 8**
```suggestion
**All UI5 Tooling Modules Require Node.js >= 16.13.2 / npm >= 8**
```

2022-04-04 12:20 UTC, KlattG commented on docs/updates/migrate-v3.md
> +*Disabled by default. Can be activated by certain build modes, project configuration or by using the `--include-task` [CLI parameter](../pages/CLI.md#ui5-build). See footnotes where given*
```suggestion
*Disabled by default. Can be activated by certain build modes, the project configuration, or by using the `--include-task` [CLI parameter](../pages/CLI.md#ui5-build). See footnotes where given* 
```

2022-04-05 09:59 UTC, KlattG commented
LGTM

2022-04-05 10:00 UTC, KlattG approved these changes

2022-04-05 12:27 UTC, codeworrior approved these changes
LGTM

2022-04-06 07:06 UTC, codeworrior approved these changes
LEBTM ;-)

2022-04-06 07:08 UTC, ecker approved these changes
LGTM, well done!

2022-04-06 07:10 UTC, merged

2022-04-06 12:37 UTC, KlattG reviewed
LGTM