[INTERNAL] UI5 Tooling v4 migration guide
SAP/ui5-tooling pull request #968
Opened 2024-06-24 11:08 UTC by d3xter666

JIRA: CPOUI5FOUNDATION-847

Some of the required documentation would be handled with: https://github.com/SAP/ui5-tooling/pull/963

2024-06-24 13:35 UTC, flovogt requested changes

2024-06-25 07:46 UTC, KlattG requested changes

2024-06-25 07:46 UTC, KlattG commented on docs/updates/migrate-v4.md
> +Support for older Node.js and npm releases has been dropped and will cause an error to be shown.
```suggestion
Support for older Node.js and npm releases has been dropped and will cause an error.
```

2024-06-25 07:46 UTC, KlattG commented on docs/updates/migrate-v4.md
> +In case a legacy specification version is detected, **an automatic migration is attempted.**
```suggestion
If a legacy specification version is detected, **an automatic migration is attempted.**
```

2024-06-25 07:46 UTC, KlattG commented on docs/updates/migrate-v4.md
> +This means your old projects might still work. Unless they have non-standard configuration in their ui5.yaml.
```suggestion
Your old projects might therefore still work unless they have a non-standard configuration in their ui5.yaml.
```

2024-06-25 07:46 UTC, KlattG commented on docs/updates/migrate-v4.md
> +* **Breaking Change:** Remove bundle option `usePredefineCalls`. UI5 CLI v4.0.0 and above will always use `sap.ui.predefine` calls in bundles, making this option obsolete. See [Configuration](../page
```suggestion
* **Breaking Change:** Remove the bundle option `usePredefineCalls`. UI5 CLI v4.0.0 and above will always use `sap.ui.predefine` calls in bundles, making this option obsolete. See [Configuration](../pages/Configuration.md#properties) for details.
```

2024-06-25 07:46 UTC, KlattG commented on docs/updates/migrate-v4.md
> +* **Breaking Change:** New option `async` for `builder.bundles.bundleDefinition.section`. Only applicable if mode = “require”. Default value `true`. See [Configuration: `bundleDefinition.section`](..
```suggestion
* **Breaking Change:** New `async` option for `builder.bundles.bundleDefinition.section` with default value = `true`; only applicable if mode = “require”. See [Configuration: `bundleDefinition.section`](../pages/Configuration.md#properties) for details.
```

2024-06-25 07:46 UTC, KlattG commented on docs/updates/migrate-v4.md
> +Occurrences of `console.log` in the codebase are replaced with `process.stderr`.
```suggestion
Occurrences of `console.log` in the code base are replaced with `process.stderr`.
```

2024-06-25 07:46 UTC, KlattG commented on docs/updates/migrate-v4.md
> +Non-public DuplexCollection#byGlobSource API has been removed.
```suggestion
Non-public `DuplexCollection#byGlobSource` API has been removed.
```

2024-06-25 07:46 UTC, KlattG commented on docs/updates/migrate-v4.md
> +- **Task API**: The `namespace` option has been renamed to `projectNamespace`. Check documentation for [CustomTasks API](../pages/extensibility/CustomTasks.md#task-implementation)
```suggestion
- **Task API**: The `namespace` option has been renamed to `projectNamespace`. For more information, check the documentation for [CustomTasks API](../pages/extensibility/CustomTasks.md#task-implementation)  
```

2024-06-25 09:16 UTC, RandomByte requested changes

2024-06-25 09:16 UTC, RandomByte commented on docs/updates/migrate-v4.md
> +    ✅ Projects defining **Specification Version 3.x** are expected to be **fully compatible with UI5 Tooling v4**
```suggestion
    ✅ Projects defining **Specification Version 2.x** are expected to be **fully compatible with UI5 Tooling v4**
```

There shouldn't be any difference between Specification Version 2 and 3 in this regard

2024-06-25 09:16 UTC, RandomByte commented on docs/updates/migrate-v4.md
> +* **Breaking Change:** New `async` option for `builder.bundles.bundleDefinition.section` with default value = `true`; only applicable if mode = “require”. See [Configuration: `bundleDefinition.sectio
```suggestion
* **Breaking Change:** New `async` option for `builder.bundles.bundleDefinition.section` with default value = `true`; only applicable if mode = "require". See [Configuration: `bundleDefinition.section`](../pages/Configuration.md#properties) for details.
```

2024-06-25 09:31 UTC, RandomByte approved these changes

2024-06-26 07:32 UTC, merged